#生产环境
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


#Github授权登录配置
github:
  client:
    id: 45dad671d252bed2e086
    secret: 48e811e0a761125a7d1213ddddba3d274b46a939
  redirect:
    uri: http://localhost:80/callback